shallow_clone: true
version: '{build}'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --production
  - npm install read-remove-file tape
build: off
test_script: node --strong_mode --throw-deprecation --track-heap-objects test.js
cache: node_modules -> package.json
